import type { Metadata } from 'next';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const isZh = locale === 'zh';

  return {
    title: isZh ? '3D模型演示 - 查看AI生成效果' : '3D Model Demo - See AI Generation Results',
    description: isZh
      ? '体验Morphix AI生成的高质量3D模型。实时预览、360度旋转查看，感受AI 3D生成的强大能力。'
      : 'Experience high-quality 3D models generated by Morphix AI. Real-time preview, 360-degree rotation view, feel the power of AI 3D generation.',
    alternates: {
      canonical: `https://www.morphix-ai.com/${locale}/demo`,
      languages: {
        en: 'https://www.morphix-ai.com/en/demo',
        zh: 'https://www.morphix-ai.com/zh/demo',
      },
    },
    openGraph: {
      title: isZh ? '3D模型演示 - Morphix AI' : '3D Model Demo - Morphix AI',
      description: isZh
        ? '体验Morphix AI生成的高质量3D模型。'
        : 'Experience high-quality 3D models generated by Morphix AI.',
      url: `https://www.morphix-ai.com/${locale}/demo`,
    },
  };
}

export default function DemoLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
