'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { useLocale } from 'next-intl';
import { createClient } from '@/lib/supabase/client';
import { Shield, Printer, CheckCircle } from 'lucide-react';
import Link from 'next/link';

interface LicenseData {
  id: string;
  created_at: string;
  model_url: string;
  source_image_url: string;
  user_email: string;
}

export default function LicensePage() {
  const params = useParams();
  const locale = useLocale();
  const [license, setLicense] = useState<LicenseData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchLicense = async () => {
      const supabase = createClient();
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        setError('Unauthorized');
        setLoading(false);
        return;
      }

      const { data, error: fetchError } = await supabase
        .from('generations')
        .select('id, created_at, model_url, source_image_url')
        .eq('id', params.id)
        .eq('user_id', user.id)
        .eq('has_license', true)
        .single();

      if (fetchError || !data) {
        setError('License not found or not authorized');
        setLoading(false);
        return;
      }

      setLicense({
        ...data,
        user_email: user.email || 'Unknown',
      });
      setLoading(false);
    };

    fetchLicense();
  }, [params.id]);

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center">
        <div className="animate-spin w-8 h-8 border-2 border-cyan-500 border-t-transparent rounded-full" />
      </div>
    );
  }

  if (error || !license) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center">
        <div className="text-center">
          <Shield className="w-16 h-16 text-red-500 mx-auto mb-4" />
          <h1 className="text-2xl font-bold text-white mb-2">
            {locale === 'zh' ? '授权证书未找到' : 'License Not Found'}
          </h1>
          <p className="text-gray-400 mb-6">{error}</p>
          <Link href={`/${locale}/dashboard`}>
            <button className="px-6 py-2 bg-cyan-500 text-white rounded-lg hover:bg-cyan-400 transition">
              {locale === 'zh' ? '返回控制台' : 'Back to Dashboard'}
            </button>
          </Link>
        </div>
      </div>
    );
  }

  const licenseDate = new Date(license.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const licenseNumber = `MX-${license.id.substring(0, 8).toUpperCase()}`;

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-900 to-black py-12 px-4">
      {/* Print Button - Hidden in print */}
      <div className="max-w-3xl mx-auto mb-6 flex justify-end gap-4 print:hidden">
        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-4 py-2 bg-cyan-500 text-white rounded-lg hover:bg-cyan-400 transition"
        >
          <Printer className="w-4 h-4" />
          {locale === 'zh' ? '打印证书' : 'Print License'}
        </button>
      </div>

      {/* License Certificate */}
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-2xl overflow-hidden print:shadow-none">
        {/* Header */}
        <div className="bg-gradient-to-r from-cyan-600 to-purple-600 p-8 text-center">
          <Shield className="w-16 h-16 text-white mx-auto mb-4" />
          <h1 className="text-3xl font-bold text-white tracking-wider">
            COMMERCIAL LICENSE
          </h1>
          <p className="text-cyan-100 mt-2">MORPHIX AI - 3D MODEL GENERATION</p>
        </div>

        {/* Content */}
        <div className="p-8 space-y-8">
          {/* License Info */}
          <div className="text-center border-b border-gray-200 pb-8">
            <p className="text-gray-500 text-sm uppercase tracking-wider mb-2">License Number</p>
            <p className="text-2xl font-mono font-bold text-gray-800">{licenseNumber}</p>
          </div>

          {/* Grant Statement */}
          <div className="text-center">
            <p className="text-gray-600 leading-relaxed">
              This certificate grants the holder a <strong>non-exclusive, worldwide, perpetual license</strong> to use the 3D model generated by Morphix AI for commercial purposes, including but not limited to:
            </p>
          </div>

          {/* Rights */}
          <div className="grid grid-cols-2 gap-4">
            {[
              'Commercial Products',
              'Marketing Materials',
              'Video Games',
              'Films & Animation',
              'Merchandise',
              'Digital Assets',
            ].map((right) => (
              <div key={right} className="flex items-center gap-2 text-gray-700">
                <CheckCircle className="w-5 h-5 text-green-500" />
                <span>{right}</span>
              </div>
            ))}
          </div>

          {/* Details */}
          <div className="bg-gray-50 rounded-xl p-6 space-y-4">
            <div className="flex justify-between">
              <span className="text-gray-500">Licensee:</span>
              <span className="font-medium text-gray-800">{license.user_email}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-500">Issue Date:</span>
              <span className="font-medium text-gray-800">{licenseDate}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-500">Model ID:</span>
              <span className="font-mono text-gray-800">{license.id}</span>
            </div>
          </div>

          {/* Footer */}
          <div className="text-center text-gray-400 text-sm pt-4 border-t border-gray-200">
            <p>This license is valid indefinitely and is non-transferable.</p>
            <p className="mt-2">© 2025 Morphix AI. All rights reserved.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
